# Generated by Django 6.0 on 2026-01-01 17:25

import django.db.models.functions.json
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='json_data',
            field=models.GeneratedField(db_persist=True, expression=django.db.models.functions.json.JSONObject(car_model_id=models.F('model_id'), id=models.F('id'), owner=models.F('owner'), vin=models.F('vin')), output_field=models.JSONField()),
        ),
        migrations.AddField(
            model_name='carmodel',
            name='json_data',
            field=models.GeneratedField(db_persist=True, expression=django.db.models.functions.json.JSONObject(car_model_name=models.F('name'), car_model_year=models.F('year'), color=models.F('color')), output_field=models.JSONField()),
        ),
    ]
